variables:
  MYSQL_DATABASE: School
  MYSQL_USER: root
  MYSQL_ROOT_PASSWORD: ''
  MYSQL_ALLOW_EMPTY_PASSWORD: 1

before_script:
  - npm install -g flow-bin
  - cd server && npm install
test:
  image: node:latest
  services:
    - mysql:5 # The JS mysql-library does not yet support the newest mysql protocol
  script:
    - npm test
