image: node:latest

# Set up MySQL test-database
services:
  - mysql:5.5

# Configure test-database
variables:
  MYSQL_DATABASE: jegharproblemer
  MYSQL_ROOT_PASSWORD: secret

# Install node libraries
before_script:
  - cd server
  - npm install

# Run JEST tests
run_tests:
  stage: test
  script:
    - npm test && npm run flow check src
 #   - cd ../client && npm install && npm test && flow check src
